### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by shortcutter** [Tobalation/RaycastVehicleTest#1]
Hi,

Thank you for sharing your work.
i am very interesting to use your work as a base for a very simple simulator in which i need tank track (and maybe try to create a rope/chain from this).
Can you please add a licence file to know what is allow?

Thank you again for you work,
TO

**Comment by Tobalation** [comment]
I forgot to add that. All the assets are under the MIT license. but if you end up using these assets in a project, credits would be greatly appreciated.
